/**
 * HomeRemediesSheet Component
 * Bottom sheet with a personalized home remedies checklist based on symptoms.
 *
 * Remedy content comes from the backend (src/lib/agents/tools/remedies-tool.ts
 * in carebow-main), not a bundled local list — the backend filters out
 * anything unsafe for this specific patient (pregnancy, diabetes, age,
 * allergies) before it ever reaches this screen. The old inline list here had
 * no such filtering at all.
 */

import React, { useCallback, useEffect, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Modal,
  Pressable,
  ScrollView,
  Share,
  Alert,
  ActivityIndicator,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Icon from 'react-native-vector-icons/Ionicons';
import { colors, spacing, radius, typography, shadows } from '../../theme';
import type { TriageLevel } from '../../utils/triageCTAMapping';
import { getRemediesForSymptom } from '../../lib/askCarebow/remediesClient';
import type { Remedy } from '../../services/api/endpoints/remedies';

interface HomeRemediesSheetProps {
  visible: boolean;
  onClose: () => void;
  symptoms?: string[];
  triageLevel?: TriageLevel;
  profileId?: string;
}

type LoadState = 'idle' | 'loading' | 'loaded' | 'empty' | 'error';

export function HomeRemediesSheet({
  visible,
  onClose,
  symptoms = [],
  profileId,
}: HomeRemediesSheetProps) {
  const insets = useSafeAreaInsets();
  const [checkedItems, setCheckedItems] = useState<Set<string>>(new Set());
  const [loadState, setLoadState] = useState<LoadState>('idle');
  const [remedies, setRemedies] = useState<Remedy[]>([]);
  const [warningSignsToWatch, setWarningSignsToWatch] = useState<string[]>([]);
  const [lifestyleAdvice, setLifestyleAdvice] = useState<string[]>([]);
  const [withheld, setWithheld] = useState<{ name: string; reason: string }[]>([]);
  const [disclaimer, setDisclaimer] = useState<string>(
    'Traditional self-care, not medical advice or a diagnosis. If symptoms are severe, ' +
      'worsening, or last more than a few days, see a clinician.'
  );
  const [fromCache, setFromCache] = useState(false);

  const primarySymptom = symptoms[0];

  const load = useCallback(async () => {
    if (!primarySymptom) {
      setLoadState('empty');
      return;
    }
    setLoadState('loading');
    const result = await getRemediesForSymptom({ symptom: primarySymptom, profileId });
    if (!result || !result.data.remedies?.length) {
      setRemedies([]);
      setLoadState('empty');
      return;
    }
    setRemedies(result.data.remedies);
    setWarningSignsToWatch(result.data.warningSignsToWatch ?? []);
    setLifestyleAdvice(result.data.lifestyleAdvice ?? []);
    setWithheld(result.data.withheld ?? []);
    if (result.data.disclaimer) setDisclaimer(result.data.disclaimer);
    setFromCache(result.fromCache);
    setLoadState('loaded');
  }, [primarySymptom, profileId]);

  useEffect(() => {
    if (visible) load();
  }, [visible, load]);

  const toggleItem = (id: string) => {
    setCheckedItems((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        newSet.delete(id);
      } else {
        newSet.add(id);
      }
      return newSet;
    });
  };

  const handleShare = async () => {
    const checkedRemedies = remedies.filter((r) => checkedItems.has(r.name));
    const remedyList = checkedRemedies.length > 0 ? checkedRemedies : remedies;

    const message = `My Home Care Checklist\n\n${remedyList
      .map((r, i) => `${i + 1}. ${r.name}\n   ${r.howTo}`)
      .join('\n\n')}\n\nGenerated by CareBow`;

    try {
      await Share.share({ message, title: 'Home Care Checklist' });
    } catch {
      Alert.alert('Unable to Share', 'There was an error sharing your checklist.');
    }
  };

  const progressPercentage =
    remedies.length > 0 ? Math.round((checkedItems.size / remedies.length) * 100) : 0;

  return (
    <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}>
      <Pressable style={styles.overlay} onPress={onClose}>
        <Pressable
          style={[styles.sheet, { paddingBottom: insets.bottom + spacing.lg }]}
          onPress={(e) => e.stopPropagation()}
        >
          <View style={styles.handleContainer}>
            <View style={styles.handle} />
          </View>

          <View style={styles.header}>
            <View style={styles.headerLeft}>
              <View style={styles.iconContainer}>
                <Icon name="list" size={24} color={colors.accent} />
              </View>
              <View>
                <Text style={styles.title}>Home Care Checklist</Text>
                <Text style={styles.subtitle}>
                  {loadState === 'loaded'
                    ? `${checkedItems.size} of ${remedies.length} completed`
                    : ' '}
                </Text>
              </View>
            </View>
            {loadState === 'loaded' && (
              <TouchableOpacity
                style={styles.shareButton}
                onPress={handleShare}
                accessibilityLabel="Share checklist"
                accessibilityRole="button"
              >
                <Icon name="share-outline" size={20} color={colors.accent} />
              </TouchableOpacity>
            )}
          </View>

          {loadState === 'loaded' && (
            <View style={styles.progressContainer}>
              <View style={styles.progressBar}>
                <View style={[styles.progressFill, { width: `${progressPercentage}%` }]} />
              </View>
              <Text style={styles.progressText}>{progressPercentage}%</Text>
            </View>
          )}

          <View style={styles.disclaimer}>
            <Icon name="information-circle" size={16} color={colors.textTertiary} />
            <Text style={styles.disclaimerText}>
              {disclaimer}
              {fromCache ? ' (showing the last saved version — you appear to be offline.)' : ''}
            </Text>
          </View>

          {loadState === 'loading' && (
            <View style={styles.centerState}>
              <ActivityIndicator color={colors.accent} />
              <Text style={styles.centerStateText}>Finding safe remedies for you…</Text>
            </View>
          )}

          {loadState === 'empty' && (
            <View style={styles.centerState}>
              <Icon name="cloud-offline-outline" size={28} color={colors.textTertiary} />
              <Text style={styles.centerStateText}>
                {primarySymptom
                  ? "We couldn't find a saved remedy for this right now — try again once you're back online, or talk to a doctor."
                  : 'Describe your symptom first so we can suggest something safe.'}
              </Text>
            </View>
          )}

          {loadState === 'loaded' && (
            <>
              <ScrollView
                style={styles.scrollView}
                showsVerticalScrollIndicator={false}
                contentContainerStyle={styles.scrollContent}
              >
                {remedies.map((remedy) => {
                  const isChecked = checkedItems.has(remedy.name);

                  return (
                    <TouchableOpacity
                      key={remedy.name}
                      style={[styles.remedyItem, isChecked && styles.remedyItemChecked]}
                      onPress={() => toggleItem(remedy.name)}
                      activeOpacity={0.7}
                      accessibilityRole="checkbox"
                      accessibilityState={{ checked: isChecked }}
                      accessibilityLabel={`${remedy.name}. ${remedy.description}`}
                    >
                      <View style={[styles.checkbox, isChecked && styles.checkboxChecked]}>
                        {isChecked && (
                          <Icon name="checkmark" size={14} color={colors.textInverse} />
                        )}
                      </View>

                      <View style={styles.remedyContent}>
                        <View style={styles.remedyHeader}>
                          <Text
                            style={[styles.remedyTitle, isChecked && styles.remedyTitleChecked]}
                          >
                            {remedy.name}
                          </Text>
                          <View style={styles.categoryBadge}>
                            <Text style={styles.categoryText}>{remedy.evidenceLevel}</Text>
                          </View>
                        </View>
                        <Text
                          style={[
                            styles.remedyDescription,
                            isChecked && styles.remedyDescriptionChecked,
                          ]}
                        >
                          {remedy.howTo}
                        </Text>
                        {!!remedy.timing && (
                          <Text style={styles.remedyTiming}>{remedy.timing}</Text>
                        )}
                      </View>
                    </TouchableOpacity>
                  );
                })}

                {warningSignsToWatch.length > 0 && (
                  <View style={styles.warningBox}>
                    <View style={styles.warningHeader}>
                      <Icon name="warning" size={16} color={colors.warning || '#B45309'} />
                      <Text style={styles.warningTitle}>Stop self-treating and see someone if</Text>
                    </View>
                    {warningSignsToWatch.map((sign) => (
                      <Text key={sign} style={styles.warningItem}>
                        • {sign}
                      </Text>
                    ))}
                  </View>
                )}

                {lifestyleAdvice.length > 0 && (
                  <View style={styles.lifestyleBox}>
                    {lifestyleAdvice.map((tip) => (
                      <Text key={tip} style={styles.lifestyleItem}>
                        • {tip}
                      </Text>
                    ))}
                  </View>
                )}

                {withheld.length > 0 && (
                  <Text style={styles.withheldText}>
                    {withheld.length} remedy suggestion{withheld.length > 1 ? 's' : ''} not shown —
                    may not be safe for you ({withheld.map((w) => w.name).join(', ')}).
                  </Text>
                )}
              </ScrollView>
            </>
          )}

          <TouchableOpacity style={styles.closeButton} onPress={onClose} activeOpacity={0.8}>
            <Text style={styles.closeButtonText}>Done</Text>
          </TouchableOpacity>
        </Pressable>
      </Pressable>
    </Modal>
  );
}

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    maxHeight: '85%',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
  },
  handleContainer: {
    alignItems: 'center',
    paddingVertical: spacing.xs,
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: radius.md,
    backgroundColor: colors.accentMuted,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    ...typography.h3,
    color: colors.textPrimary,
  },
  subtitle: {
    ...typography.caption,
    color: colors.textTertiary,
  },
  shareButton: {
    width: 40,
    height: 40,
    borderRadius: radius.md,
    backgroundColor: colors.accentMuted,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  progressBar: {
    flex: 1,
    height: 6,
    backgroundColor: colors.surface2,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.success,
    borderRadius: 3,
  },
  progressText: {
    ...typography.caption,
    color: colors.textTertiary,
    width: 36,
    textAlign: 'right',
  },
  disclaimer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.xs,
    backgroundColor: colors.surface2,
    borderRadius: radius.md,
    padding: spacing.sm,
    marginBottom: spacing.md,
  },
  disclaimerText: {
    ...typography.caption,
    color: colors.textTertiary,
    flex: 1,
    lineHeight: 18,
  },
  centerState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xl,
    gap: spacing.sm,
  },
  centerStateText: {
    ...typography.caption,
    color: colors.textTertiary,
    textAlign: 'center',
    paddingHorizontal: spacing.lg,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: spacing.md,
  },
  remedyItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: spacing.md,
    backgroundColor: colors.background,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  remedyItemChecked: {
    backgroundColor: colors.successSoft || '#F0FDF4',
    borderColor: colors.success,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm,
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: colors.success,
    borderColor: colors.success,
  },
  remedyContent: {
    flex: 1,
  },
  remedyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.xxs,
  },
  remedyTitle: {
    ...typography.label,
    color: colors.textPrimary,
    flex: 1,
  },
  remedyTitleChecked: {
    textDecorationLine: 'line-through',
    color: colors.textTertiary,
  },
  categoryBadge: {
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
    borderRadius: radius.sm,
    marginLeft: spacing.xs,
    backgroundColor: colors.accentMuted,
  },
  categoryText: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.accent,
  },
  remedyDescription: {
    ...typography.caption,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  remedyDescriptionChecked: {
    color: colors.textTertiary,
  },
  remedyTiming: {
    ...typography.caption,
    color: colors.textTertiary,
    marginTop: 2,
    fontStyle: 'italic',
  },
  warningBox: {
    backgroundColor: '#FEF3C7',
    borderRadius: radius.md,
    padding: spacing.sm,
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
  warningHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.xs,
  },
  warningTitle: {
    ...typography.label,
    color: '#92400E',
  },
  warningItem: {
    ...typography.caption,
    color: '#92400E',
    lineHeight: 18,
  },
  lifestyleBox: {
    marginBottom: spacing.sm,
  },
  lifestyleItem: {
    ...typography.caption,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  withheldText: {
    ...typography.caption,
    color: colors.textTertiary,
    fontStyle: 'italic',
    marginBottom: spacing.sm,
  },
  closeButton: {
    backgroundColor: colors.accent,
    borderRadius: radius.md,
    paddingVertical: spacing.md,
    alignItems: 'center',
    marginTop: spacing.sm,
    ...shadows.button,
  },
  closeButtonText: {
    ...typography.labelLarge,
    color: colors.textInverse,
  },
});

export default HomeRemediesSheet;
